# Generated by Django 5.2.4 on 2025-07-24 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0002_alter_homework_is_completed'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Homework',
            new_name='Todo',
        ),
    ]
