# Generated by Django 5.2.4 on 2025-07-30 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0004_todo_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='User',
            new_name='user',
        ),
    ]
