# Generated by Django 5.2.4 on 2025-08-04 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0007_alter_comment_todo'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='completed_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d', verbose_name='완료이미지'),
        ),
        migrations.AddField(
            model_name='todo',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d/thumbnail', verbose_name='썸네일'),
        ),
    ]
